# Generated by Django 4.2.20 on 2025-04-27 21:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customuser_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='is_verfied',
            new_name='is_verified',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 11 digits.', regex='^\\d{11}$')]),
        ),
    ]
